server:
  port: ${PORT:8084}
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://bruno:bruno@cluster0.u1cky.mongodb.net/client?retryWrites=true&w=majority
managment:
  endpoint:
    web:
      exposure:
        include:
eureka: 
  client:
    service-url:
      defaultZone: https://thawing-garden-19877.herokuapp.com/eureka/
logging:
  level:
    root: info
    org:
      springframework:
        web: info 
        data: 
          mongodb:
            core: 
              ReactiveMongoTemplate: DEBUG