server:
  port: ${PORT:8083}
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://bruno:bruno@cluster0.u1cky.mongodb.net/product?retryWrites=true&w=majority
managment:
  endpoint:
    web:
      exposure:
        include:
