server:
  port: ${PORT:8083}
spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://dbcliente:dbcliente@cluster0.lfrvs.mongodb.net/client?retryWrites=true&w=majority
managment:
  endpoint:
    web:
      exposure:
        include:
